### ISSUE TITLE
Error when using the spatialization operators

### ISSUE THREAD

**Issue by roubaisk** [ANRGenstar/genstar.gamaplugin#9]
Hi,

I am getting an error message when trying to execute any of the Genstar plugin templates that include spatialization operators: genstar-poc.gaml, Rouen_template-localisation_2.gaml, and also the templates in the test folder that use geographical entities.

This is a copy of the error message (when trying to run the Rouen_template_localisation_2.gaml):

2 occurrences in 2 agents at cycle 0: Java error: NoClassDefFoundError
in create people from: pop_gen number: 10000 ;
NoClassDefFoundError: org/apache/poi/ss/formula/eval/NotImplementedException
spll.entity.GeoEntityFactory.createGeoEntity(GeoEntityFactory.java:157)
spll.io.SPLVectorFile.<init>(SPLVectorFile.java:115)
spll.io.SPLVectorFile.<init>(SPLVectorFile.java:126)
spll.io.SPLGeofileBuilder.getShapeFile(SPLGeofileBuilder.java:559)
genstar.gamaplugin.operators.GenstarGenerationOperators.spatializePopulation(GenstarGenerationOperators.java:327)
genstar.gamaplugin.operators.GenstarGenerationOperators.generatePop(GenstarGenerationOperators.java:183)
genstar.gamaplugin.statements.CreateFromGenstarDelegate.createFrom(CreateFromGenstarDelegate.java:84)
in agents Simulation 0, Rouentemplate0

I am currently working with GAMA 1.8.1.

Could you please look into this issue?
Best,
Rouba

**Comment by chapuisk** [comment]
Dear @roubaisk ,
In fact I get the same error, and I suspected previous attempt to use Gama species to localize agent as the source of the error. It was the case, so this commit 4f225860619757a8f7c38ddbe49b162fc0e944b6 had isolated the bug.
The Plugin used with the Git version of Gama is ok. You'll have to wait a little bit for the updatesite to be updated.
Best,
Kevin
